services:
  # Caddy reverse proxy
  caddy: !override
    image: traefik:v2.11
    command:
      - "--ping=true"
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      - "--accesslog=true"
      - "--accesslog.filepath=/tmp/access.log"
      - "--certificatesResolvers.http.acme.email=admin@${NETBIRD_DOMAIN}"
      - "--certificatesresolvers.http.acme.storage=/traefik/acme.http.json"
      - "--certificatesresolvers.http.acme.httpChallenge=true"
      - "--certificatesresolvers.http.acme.httpChallenge.entryPoint=web"
      - "--experimental.plugins.rewrite-body.modulename=github.com/packruler/rewrite-body"
      - "--experimental.plugins.rewrite-body.version=v1.2.0"
      - "--experimental.plugins.cookiePathRewrite.modulename=github.com/vnghia/traefik-plugin-rewrite-cookie-path"
      - "--experimental.plugins.cookiePathRewrite.version=v0.0.1"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`project.name`, `netbird`)"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.forwardedheaders.trustedips=0.0.0.0/0"
      - "--entryPoints.websecure.forwardedHeaders.insecure"
      - "--entrypoints.websecure.address=:443"
    restart: always
    networks:
      netbird: null
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    ports:
      - "${TRAEFIK_BIND_ADDRESS_HTTP:-0.0.0.0}:${TRAEFIK_BIND_PORT_HTTP:-80}:80"
      - "${TRAEFIK_BIND_ADDRESS_HTTPS:-0.0.0.0}:${TRAEFIK_BIND_PORT_HTTP:-443}:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "netbird_caddy_data:/traefik"
    labels:
      project.name: 'netbird'
      traefik.enable: 'true'
      traefik.http.routers.traefik-api-web.rule: 'Host(`${NETBIRD_DOMAIN}`) && (PathPrefix(`/traefik/dashboard`) || (PathPrefix(`/api`) && HeadersRegexp(`referer`, `/traefik/dashboard`)))'
      traefik.http.routers.traefik-api-web.entrypoints: "web"
      traefik.http.routers.traefik-api-web.middlewares: "redirect-secure"
      traefik.http.routers.traefik-api-web.priority: 9000
      traefik.http.routers.traefik-api-websecure.rule: 'Host(`${NETBIRD_DOMAIN}`) && (PathPrefix(`/traefik/dashboard`) || (PathPrefix(`/api`) && HeadersRegexp(`referer`, `/traefik/dashboard`)))'
      traefik.http.routers.traefik-api-websecure.priority: 9000
      traefik.http.routers.traefik-api-websecure.entrypoints: "websecure"
      traefik.http.routers.traefik-api-websecure.service: "api@internal"
      traefik.http.routers.traefik-api-websecure.middlewares: "traefik-api-stripprefix,traefik-api-auth"
      traefik.http.routers.traefik-api-websecure.tls: "true"
      traefik.http.routers.traefik-api-websecure.tls.certresolver: "http"
      traefik.http.routers.traefik-api-websecure.tls.domains[0].main: "${NETBIRD_DOMAIN}"
      traefik.http.middlewares.traefik-api-stripprefix.stripprefix.prefixes: "/traefik"
      traefik.http.middlewares.traefik-api-auth.basicauth.users: "admin:{SHA}0tTNr469Z7oY3fDRwNoUXE2vTBw="
      traefik.http.middlewares.redirect-secure.redirectregex.regex: "^(http|ws):\\/\\/(.+)$$"
      traefik.http.middlewares.redirect-secure.redirectregex.replacement: "$${1}s://$${2}"
      traefik.http.middlewares.redirect-secure.redirectregex.permanent: "true"
    healthcheck:
      test: traefik healthcheck --ping
      start_period: 5s

  # UI dashboard
  dashboard:
    depends_on:
      caddy:
        condition: 'service_healthy'
    labels:
      project.name: "netbird"
      traefik.enable: "true"
      traefik.http.routers.dashboard-web.rule: 'Host(`${NETBIRD_DOMAIN}`) && PathPrefix(`/`)'
      traefik.http.routers.dashboard-web.entrypoints: "web"
      traefik.http.routers.dashboard-web.middlewares: "redirect-secure"
      traefik.http.routers.dashboard-web.priority: 1000
      traefik.http.routers.dashboard-websecure.rule: 'Host(`${NETBIRD_DOMAIN}`) && PathPrefix(`/`)'
      traefik.http.routers.dashboard-websecure.priority: 1000
      traefik.http.routers.dashboard-websecure.entrypoints: "websecure"
      traefik.http.routers.dashboard-websecure.service: "dashboard"
      traefik.http.routers.dashboard-websecure.tls: "true"
      traefik.http.routers.dashboard-websecure.tls.certresolver: "http"
      traefik.http.routers.dashboard-websecure.tls.domains[0].main: "${NETBIRD_DOMAIN}"
      traefik.http.services.dashboard.loadbalancer.server.port: "80"

  # Signal
  signal:
    depends_on:
      caddy:
        condition: 'service_healthy'
    labels:
      project.name: "netbird"
      traefik.enable: "true"
      traefik.http.routers.signal-web.rule: 'Host(`${NETBIRD_DOMAIN}`) && (PathPrefix(`/signalexchange`))'
      traefik.http.routers.signal-web.entrypoints: "web"
      traefik.http.routers.signal-web.service: "signal-web"
      traefik.http.routers.signal-web.priority: 4000
      traefik.http.routers.signal-websecure.rule: 'Host(`${NETBIRD_DOMAIN}`) && (PathPrefix(`/signalexchange`))'
      traefik.http.routers.signal-websecure.priority: 4000
      traefik.http.routers.signal-websecure.entrypoints: "websecure"
      traefik.http.routers.signal-websecure.service: "signal"
      traefik.http.routers.signal-websecure.tls: "true"
      traefik.http.routers.signal-websecure.tls.certresolver: "http"
      traefik.http.routers.signal-websecure.tls.domains[0].main: "${NETBIRD_DOMAIN}"
      traefik.http.services.signal-web.loadbalancer.server.port: "80"
      traefik.http.services.signal.loadbalancer.server.scheme: "h2c"
      traefik.http.services.signal.loadbalancer.server.port: "10000"

  # Relay
  relay:
    depends_on:
      caddy:
        condition: 'service_healthy'
    labels:
      project.name: "netbird"
      traefik.enable: "true"
      traefik.http.routers.relay-web.rule: 'Host(`${NETBIRD_DOMAIN}`) && (PathPrefix(`/relay`))'
      traefik.http.routers.relay-web.entrypoints: "web"
      traefik.http.routers.relay-web.middlewares: "redirect-secure"
      traefik.http.routers.relay-web.priority: 4000
      traefik.http.routers.relay-websecure.rule: 'Host(`${NETBIRD_DOMAIN}`) && (PathPrefix(`/relay`))'
      traefik.http.routers.relay-websecure.priority: 4000
      traefik.http.routers.relay-websecure.entrypoints: "websecure"
      traefik.http.routers.relay-websecure.service: "relay"
      traefik.http.routers.relay-websecure.tls: "true"
      traefik.http.routers.relay-websecure.tls.certresolver: "http"
      traefik.http.routers.relay-websecure.tls.domains[0].main: "${NETBIRD_DOMAIN}"
      traefik.http.services.relay.loadbalancer.server.port: "80"

  # Management
  management:
    command: [
      "--port", "80",
      "--log-file", "console",
      "--log-level", "info",
      "--disable-anonymous-metrics=false",
      "--single-account-mode-domain=netbird.selfhosted",
      "--dns-domain=netbird.selfhosted",
      "--idp-sign-key-refresh-enabled",
    ]
    depends_on:
      caddy:
        condition: 'service_healthy'
    labels:
      project.name: "netbird"
      traefik.enable: "true"
      traefik.http.routers.management-web.rule: 'Host(`${NETBIRD_DOMAIN}`) && (PathPrefix(`/management.ManagementService`) || PathPrefix(`/api/`))'
      traefik.http.routers.management-web.entrypoints: "web"
      traefik.http.routers.management-web.middlewares: "redirect-secure"
      traefik.http.routers.management-web.priority: 4000
      traefik.http.routers.management-websecure.rule: 'Host(`${NETBIRD_DOMAIN}`) && (PathPrefix(`/management.ManagementService`) || PathPrefix(`/api/`))'
      traefik.http.routers.management-websecure.priority: 4000
      traefik.http.routers.management-websecure.entrypoints: "websecure"
      traefik.http.routers.management-websecure.service: "management"
      traefik.http.routers.management-websecure.tls: "true"
      traefik.http.routers.management-websecure.tls.certresolver: "http"
      traefik.http.routers.management-websecure.tls.domains[0].main: "${NETBIRD_DOMAIN}"
      traefik.http.services.management.loadbalancer.server.scheme: "h2c"
      traefik.http.services.management.loadbalancer.server.port: "80"
      

  # Zitadel - identity provider
  zitadel:
    depends_on:
      caddy:
        condition: 'service_healthy'
    labels:
      project.name: "netbird"
      traefik.enable: "true"
      traefik.http.routers.zitadel-web.rule: 'Host(`${NETBIRD_DOMAIN}`) && (PathPrefix(`/zitadel`) || PathPrefix(`/device`) || PathPrefix(`/{path:(ui|.well-known|openapi|debug)}/`) || PathPrefix(`/{path:(admin|auth|management|system|assets|oidc|saml|oauth)/v[0-9]+/}`))'
      traefik.http.routers.zitadel-web.entrypoints: "web"
      traefik.http.routers.zitadel-web.middlewares: "redirect-secure"
      traefik.http.routers.zitadel-web.priority: 5000
      traefik.http.routers.zitadel-websecure.rule: 'Host(`${NETBIRD_DOMAIN}`) && (PathPrefix(`/zitadel`) || PathPrefix(`/device`) || PathPrefix(`/{path:(ui|.well-known|openapi|debug)}/`) || PathPrefix(`/{path:(admin|auth|management|system|assets|oidc|saml|oauth)/v[0-9]+/}`))'
      traefik.http.routers.zitadel-websecure.priority: 5000
      traefik.http.routers.zitadel-websecure.entrypoints: "websecure"
      traefik.http.routers.zitadel-websecure.service: "zitadel"
      traefik.http.routers.zitadel-websecure.tls: "true"
      traefik.http.routers.zitadel-websecure.tls.certresolver: "http"
      traefik.http.routers.zitadel-websecure.tls.domains[0].main: "${NETBIRD_DOMAIN}"
      traefik.http.services.zitadel.loadbalancer.server.scheme: "h2c"
      traefik.http.services.zitadel.loadbalancer.server.port: "8080"

  mail:
    depends_on:
      caddy:
        condition: 'service_healthy'
    healthcheck:
      test:
        - CMD-SHELL
        - nc -vz -w 1 localhost 8025
      interval: 2s
      start_period: 5s
    image: cd2team/mailhog
    environment:
      MH_UI_WEB_PATH: "mail"
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "2"
    networks:
      netbird: null
    restart: always
    labels:
      project.name: "netbird"
      traefik.enable: "true"
      traefik.http.routers.mail-web.rule: 'Host(`${NETBIRD_DOMAIN}`) && (PathPrefix(`/mail/`))'
      traefik.http.routers.mail-web.entrypoints: "web"
      traefik.http.routers.mail-web.middlewares: "redirect-secure"
      traefik.http.routers.mail-web.priority: 6000
      traefik.http.routers.mail-websecure.rule: 'Host(`${NETBIRD_DOMAIN}`) && (PathPrefix(`/mail/`))'
      traefik.http.routers.mail-websecure.priority: 6000
      traefik.http.routers.mail-websecure.entrypoints: "websecure"
      traefik.http.routers.mail-websecure.service: "mail"
      traefik.http.routers.mail-websecure.middlewares: "mail-auth"
      traefik.http.routers.mail-websecure.tls: "true"
      traefik.http.routers.mail-websecure.tls.certresolver: "http"
      traefik.http.routers.mail-websecure.tls.domains[0].main: "${NETBIRD_DOMAIN}"
      traefik.http.services.mail.loadbalancer.server.port: "8025"
      traefik.http.middlewares.mail-auth.basicauth.users: "admin:{SHA}0tTNr469Z7oY3fDRwNoUXE2vTBw="

  tinyproxy:
    image: docker.io/kalaksi/tinyproxy
    # You can also use GitLab as an alternative to Docker Hub:
    # image: registry.gitlab.com/kalaksi-containers/tinyproxy
    restart: always
    cap_drop:
      - ALL
    ports:
      - 8888:8888
    # See tinyproxy.conf for better explanation of these values.
    environment:
      # Optionally override port tinyproxy is listening on.
      # PORT: 8080
      # Set to "yes" to disable the Via-header, set to empty to leave it enabled.
      DISABLE_VIA_HEADER: 'yes'
      # Set this to e.g. tinyproxy.stats to enable stats-page on that address
      STAT_HOST: tinyproxy.stats
      MAX_CLIENTS: 100
      # A space separated list. If not set or is empty, all networks are allowed.
      ALLOWED_NETWORKS: 127.0.0.1/8 10.0.0.0/8 
      # One of Critical, Error, Warning, Notice, Connect, Info
      LOG_LEVEL: Notice
      # Maximum number of seconds idle connections are allowed to remain open
      TIMEOUT: 900
      # Username for BasicAuth
      # AUTH_USER: ''
      # Password for BasicAuth (letters and digits only)
      # Prefer secrets-mechanisms instead of environment variables.
      # AUTH_PASSWORD: ''
    # secrets:
    #   - auth_password
    # # With Alpine base image, this is required, for some reason, or /run/secrets won't get mounted.
    # tmpfs:
    #   - /run
    healthcheck:
      test: ["CMD", "curl", "-I", "-H", "Host: tinyproxy.stats", "http://localhost:8888"]
      interval: 5m
      timeout: 10s
      retries: 1
    # volumes:
    #   # If not using docker-compose for secrets, you can still manually mount a file containing the password.
    #   - ./secrets/auth_password:/run/secrets/auth_password:ro

  coturn:
    volumes:
      - netbird_coturn_data:/var/lib/coturn

volumes:
  netbird_coturn_data: